config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :create, :destroy] do
    resources :doses, only: [:new, :create]
  end
  delete '/doses/:id', to: 'doses#destroy', as: 'dose'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save

    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
     render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
    redirect_to cocktail_path(@cocktail)
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :url)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/cocktails/index.html.erb
<div class="container_cocktail">
  <div class="cocktail_banner">
    <h1 class="title_index">THE ALCHEMIST</h1>
    <div class="button_add">
        <%= link_to "Add your cocktail", new_cocktail_path, class: "btn btn-light pad20" %>
    </div>
  </div>

  <div>
    <div class="row">
      <% @cocktails.each do |cocktail| %>
        <div class="col-sm-4">
          <div class="card">
            <div class="card-body">
              <%= image_tag cocktail.url, width: 300, height: 225, crop: :fill %>
              <br> <br>
              <h5 class="card-title text-decoration-none text-info font-weight-bold"><%= link_to cocktail.name, cocktail_path(cocktail) %></h5>
              <%= link_to "Delete", cocktail_path(cocktail), class: "btn btn-outline-dark delete_button", method: :delete  %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container pt-5">
  <h1>Add a new cocktail</h1>
  <br>
    <%= simple_form_for @cocktail do |f| %>
      <%= f.input :name %>
      <%= f.input :url %>
      <%= f.submit "Submit", class: "btn btn-primary button_submit" %>
    <% end %>
    <br>
  <%= link_to "Go back", cocktails_path, class: "btn btn-outline-dark button_back" %>
</div>

app/views/cocktails/show.html.erb
<div class="container_cocktail">
  <div class="card text-center" style="width: 30%;">
    <div class="card-body">
      <%= image_tag @cocktail.url, width: 400, height: 300, crop: :fill %>
      <h5 class="card-title text-uppercase py-3"><%= @cocktail.name %></h5>
      <p class="card-text">
        <ul class="list-group">
          <% @cocktail.doses.each do |dose| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <%= dose.ingredient.name %>
              <span class="badge badge-primary badge-pill"><%= dose.description %></span>
            </li>
          <% end %>
        </ul>
      </p>
      <%= link_to "Add ingredient", new_cocktail_dose_path(@cocktail), class: "btn btn-primary", id: "ingredient-add-button"%>
      <%= link_to "Go back", cocktails_path, class: "btn btn-outline-dark" %>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container pt-5">
  <h1>Add a new dose</h1>
  <br>
    <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.association :ingredient %>
      <%= f.input :description %>
      <%= f.submit 'Add ingredient', class: 'btn btn-primary button_submit'%>
    <% end %>

  <%= link_to "Back to cocktail", cocktail_path(params[:cocktail_id]), class: 'btn btn-outline-dark button_back' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>